name: Unit test library methods
on:
  push:
    paths:
      - '**/unittestlib.yml'
      - 'lib/**'

  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-20.04, ubuntu-22.04]
        ruby: [2.7, 3.1]
    runs-on: ${{ matrix.os }}
    steps:
    - name: setup # needed for installing ruby-ldap
      run: |
        sudo apt-get install libldap2-dev
        sudo apt-get install libsasl2-dev
      if:  matrix.os != 'macos-latest'  
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: test library code
      run: |
        cd lib
        bundle install
        bundle exec rake
